export const PRODUCT_IMPORT_EXPORT_PLUGIN_OPTIONS = Symbol('PRODUCT_IMPORT_EXPORT_PLUGIN_OPTIONS')
export const EXPORT_STORAGE_STRATEGY = Symbol('EXPORT_STORAGE_STRATEGY')
export const loggerCtx = 'ProductImportExportPlugin'
